// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "Proxy_Adapter.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



Proxy_Adapter::StructConf_ptr Proxy_Adapter::StructConf_Helper::_nil() {
  return ::Proxy_Adapter::StructConf::_nil();
}

::CORBA::Boolean Proxy_Adapter::StructConf_Helper::is_nil(::Proxy_Adapter::StructConf_ptr p) {
  return ::CORBA::is_nil(p);

}

void Proxy_Adapter::StructConf_Helper::release(::Proxy_Adapter::StructConf_ptr p) {
  ::CORBA::release(p);
}

void Proxy_Adapter::StructConf_Helper::marshalObjRef(::Proxy_Adapter::StructConf_ptr obj, cdrStream& s) {
  ::Proxy_Adapter::StructConf::_marshalObjRef(obj, s);
}

Proxy_Adapter::StructConf_ptr Proxy_Adapter::StructConf_Helper::unmarshalObjRef(cdrStream& s) {
  return ::Proxy_Adapter::StructConf::_unmarshalObjRef(s);
}

void Proxy_Adapter::StructConf_Helper::duplicate(::Proxy_Adapter::StructConf_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

Proxy_Adapter::StructConf_ptr
Proxy_Adapter::StructConf::_duplicate(::Proxy_Adapter::StructConf_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

Proxy_Adapter::StructConf_ptr
Proxy_Adapter::StructConf::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


Proxy_Adapter::StructConf_ptr
Proxy_Adapter::StructConf::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

Proxy_Adapter::StructConf_ptr
Proxy_Adapter::StructConf::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_StructConf _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_StructConf* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_StructConf;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* Proxy_Adapter::StructConf::_PD_repoId = "IDL:Proxy_Adapter/StructConf:1.0";


Proxy_Adapter::_objref_StructConf::~_objref_StructConf() {
  
}


Proxy_Adapter::_objref_StructConf::_objref_StructConf(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::Proxy_Adapter::StructConf::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
Proxy_Adapter::_objref_StructConf::_ptrToObjRef(const char* id)
{
  if( id == ::Proxy_Adapter::StructConf::_PD_repoId )
    return (::Proxy_Adapter::StructConf_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::Proxy_Adapter::StructConf::_PD_repoId) )
    return (::Proxy_Adapter::StructConf_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_n_cunsigned_plong
class _0RL_cd_40eea1302de063aa_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::EZuint arg_0_;
  Proxy_Adapter::EZuint* arg_0;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_00000000::marshalArguments(cdrStream& _n)
{
  *arg_0 >>= _n;

}

void _0RL_cd_40eea1302de063aa_00000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::EZuint&)arg_0_ <<= _n;
  arg_0 = &arg_0_;

}

void _0RL_cd_40eea1302de063aa_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  *arg_0 >>= _n;

}

void _0RL_cd_40eea1302de063aa_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  (Proxy_Adapter::EZuint&)*arg_0 <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_00000000* tcd = (_0RL_cd_40eea1302de063aa_00000000*)cd;
  Proxy_Adapter::_impl_StructConf* impl = (Proxy_Adapter::_impl_StructConf*) svnt->_ptrToInterface(Proxy_Adapter::StructConf::_PD_repoId);
  tcd->result = impl->testStructConf(*tcd->arg_0);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_StructConf::testStructConf(::Proxy_Adapter::EZuint& testVal)
{
  _0RL_cd_40eea1302de063aa_00000000 _call_desc(_0RL_lcfn_40eea1302de063aa_10000000, "testStructConf", 15);
  _call_desc.arg_0 = &(::Proxy_Adapter::EZuint&) testVal;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cProxy__Adapter_mEZStruct__type_i_cunsigned_plong_i_cunsigned_plong_i_cunsigned_plong_i_cProxy__Adapter_mEZvalue_i_cProxy__Adapter_mEZvalue_i_cProxy__Adapter_mEZvalue
class _0RL_cd_40eea1302de063aa_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::EZStruct_type arg_0;
  Proxy_Adapter::EZStr_Num arg_1;
  Proxy_Adapter::KeySize arg_2;
  Proxy_Adapter::ResultSize arg_3;
  Proxy_Adapter::EZvalue_var arg_4_;
  const Proxy_Adapter::EZvalue* arg_4;
  Proxy_Adapter::EZvalue_var arg_5_;
  const Proxy_Adapter::EZvalue* arg_5;
  Proxy_Adapter::EZvalue_var arg_6_;
  const Proxy_Adapter::EZvalue* arg_6;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_20000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;
  arg_3 >>= _n;
  (const Proxy_Adapter::EZvalue&) *arg_4 >>= _n;
  (const Proxy_Adapter::EZvalue&) *arg_5 >>= _n;
  (const Proxy_Adapter::EZvalue&) *arg_6 >>= _n;

}

void _0RL_cd_40eea1302de063aa_20000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::EZStruct_type&)arg_0 <<= _n;
  (Proxy_Adapter::EZStr_Num&)arg_1 <<= _n;
  (Proxy_Adapter::KeySize&)arg_2 <<= _n;
  (Proxy_Adapter::ResultSize&)arg_3 <<= _n;
  arg_4_ = new Proxy_Adapter::EZvalue;
  (Proxy_Adapter::EZvalue&)arg_4_ <<= _n;
  arg_4 = &arg_4_.in();
  arg_5_ = new Proxy_Adapter::EZvalue;
  (Proxy_Adapter::EZvalue&)arg_5_ <<= _n;
  arg_5 = &arg_5_.in();
  arg_6_ = new Proxy_Adapter::EZvalue;
  (Proxy_Adapter::EZvalue&)arg_6_ <<= _n;
  arg_6 = &arg_6_.in();

}

void _0RL_cd_40eea1302de063aa_20000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_40eea1302de063aa_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_20000000* tcd = (_0RL_cd_40eea1302de063aa_20000000*)cd;
  Proxy_Adapter::_impl_StructConf* impl = (Proxy_Adapter::_impl_StructConf*) svnt->_ptrToInterface(Proxy_Adapter::StructConf::_PD_repoId);
  tcd->result = impl->setStructEntry(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3, *tcd->arg_4, *tcd->arg_5, *tcd->arg_6);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_StructConf::setStructEntry(::Proxy_Adapter::EZStruct_type struct_type, ::Proxy_Adapter::EZStr_Num struct_num, ::Proxy_Adapter::KeySize k_length, ::Proxy_Adapter::ResultSize r_length, const ::Proxy_Adapter::EZvalue& key, const ::Proxy_Adapter::EZvalue& result, const ::Proxy_Adapter::EZvalue& mask)
{
  _0RL_cd_40eea1302de063aa_20000000 _call_desc(_0RL_lcfn_40eea1302de063aa_30000000, "setStructEntry", 15);
  _call_desc.arg_0 = struct_type;
  _call_desc.arg_1 = struct_num;
  _call_desc.arg_2 = k_length;
  _call_desc.arg_3 = r_length;
  _call_desc.arg_4 = &(::Proxy_Adapter::EZvalue&) key;
  _call_desc.arg_5 = &(::Proxy_Adapter::EZvalue&) result;
  _call_desc.arg_6 = &(::Proxy_Adapter::EZvalue&) mask;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cProxy__Adapter_mEZStruct__type_i_cunsigned_plong_i_cunsigned_plong_n_cunsigned_plong_n_cunsigned_plong_n_cProxy__Adapter_mEZvalue_n_cProxy__Adapter_mEZvalue_n_cProxy__Adapter_mEZvalue
class _0RL_cd_40eea1302de063aa_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_40000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::EZStruct_type arg_0;
  Proxy_Adapter::EZStr_Num arg_1;
  Proxy_Adapter::uint32 arg_2;
  Proxy_Adapter::KeySize arg_3_;
  Proxy_Adapter::KeySize* arg_3;
  Proxy_Adapter::ResultSize arg_4_;
  Proxy_Adapter::ResultSize* arg_4;
  Proxy_Adapter::EZvalue_var arg_5_;
  Proxy_Adapter::EZvalue* arg_5;
  Proxy_Adapter::EZvalue_var arg_6_;
  Proxy_Adapter::EZvalue* arg_6;
  Proxy_Adapter::EZvalue_var arg_7_;
  Proxy_Adapter::EZvalue* arg_7;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_40000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;
  *arg_3 >>= _n;
  *arg_4 >>= _n;
  (const Proxy_Adapter::EZvalue&) *arg_5 >>= _n;
  (const Proxy_Adapter::EZvalue&) *arg_6 >>= _n;
  (const Proxy_Adapter::EZvalue&) *arg_7 >>= _n;

}

void _0RL_cd_40eea1302de063aa_40000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::EZStruct_type&)arg_0 <<= _n;
  (Proxy_Adapter::EZStr_Num&)arg_1 <<= _n;
  (Proxy_Adapter::uint32&)arg_2 <<= _n;
  (Proxy_Adapter::KeySize&)arg_3_ <<= _n;
  arg_3 = &arg_3_;
  (Proxy_Adapter::ResultSize&)arg_4_ <<= _n;
  arg_4 = &arg_4_;
  arg_5_ = new Proxy_Adapter::EZvalue;
  (Proxy_Adapter::EZvalue&)arg_5_ <<= _n;
  arg_5 = &arg_5_.inout();
  arg_6_ = new Proxy_Adapter::EZvalue;
  (Proxy_Adapter::EZvalue&)arg_6_ <<= _n;
  arg_6 = &arg_6_.inout();
  arg_7_ = new Proxy_Adapter::EZvalue;
  (Proxy_Adapter::EZvalue&)arg_7_ <<= _n;
  arg_7 = &arg_7_.inout();

}

void _0RL_cd_40eea1302de063aa_40000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  *arg_3 >>= _n;
  *arg_4 >>= _n;
  (const Proxy_Adapter::EZvalue&) *arg_5 >>= _n;
  (const Proxy_Adapter::EZvalue&) *arg_6 >>= _n;
  (const Proxy_Adapter::EZvalue&) *arg_7 >>= _n;

}

void _0RL_cd_40eea1302de063aa_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  (Proxy_Adapter::KeySize&)*arg_3 <<= _n;
  (Proxy_Adapter::ResultSize&)*arg_4 <<= _n;
  (Proxy_Adapter::EZvalue&)*arg_5 <<= _n;
  (Proxy_Adapter::EZvalue&)*arg_6 <<= _n;
  (Proxy_Adapter::EZvalue&)*arg_7 <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_40000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_40000000* tcd = (_0RL_cd_40eea1302de063aa_40000000*)cd;
  Proxy_Adapter::_impl_StructConf* impl = (Proxy_Adapter::_impl_StructConf*) svnt->_ptrToInterface(Proxy_Adapter::StructConf::_PD_repoId);
  tcd->result = impl->getStructEntry(tcd->arg_0, tcd->arg_1, tcd->arg_2, *tcd->arg_3, *tcd->arg_4, *tcd->arg_5, *tcd->arg_6, *tcd->arg_7);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_StructConf::getStructEntry(::Proxy_Adapter::EZStruct_type struct_type, ::Proxy_Adapter::EZStr_Num struct_num, ::Proxy_Adapter::uint32 index, ::Proxy_Adapter::KeySize& k_length, ::Proxy_Adapter::ResultSize& r_length, ::Proxy_Adapter::EZvalue& key, ::Proxy_Adapter::EZvalue& result, ::Proxy_Adapter::EZvalue& mask)
{
  _0RL_cd_40eea1302de063aa_40000000 _call_desc(_0RL_lcfn_40eea1302de063aa_50000000, "getStructEntry", 15);
  _call_desc.arg_0 = struct_type;
  _call_desc.arg_1 = struct_num;
  _call_desc.arg_2 = index;
  _call_desc.arg_3 = &(::Proxy_Adapter::KeySize&) k_length;
  _call_desc.arg_4 = &(::Proxy_Adapter::ResultSize&) r_length;
  _call_desc.arg_5 = &(::Proxy_Adapter::EZvalue&) key;
  _call_desc.arg_6 = &(::Proxy_Adapter::EZvalue&) result;
  _call_desc.arg_7 = &(::Proxy_Adapter::EZvalue&) mask;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cProxy__Adapter_mEZStruct__type_i_cunsigned_plong_i_cunsigned_plong_i_cProxy__Adapter_mEZvalue_i_cunsigned_plong_n_cProxy__Adapter_mEZvalue
class _0RL_cd_40eea1302de063aa_60000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_60000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::EZStruct_type arg_0;
  Proxy_Adapter::EZStr_Num arg_1;
  Proxy_Adapter::KeySize arg_2;
  Proxy_Adapter::EZvalue_var arg_3_;
  const Proxy_Adapter::EZvalue* arg_3;
  Proxy_Adapter::ResultSize arg_4;
  Proxy_Adapter::EZvalue_var arg_5_;
  Proxy_Adapter::EZvalue* arg_5;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_60000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;
  (const Proxy_Adapter::EZvalue&) *arg_3 >>= _n;
  arg_4 >>= _n;
  (const Proxy_Adapter::EZvalue&) *arg_5 >>= _n;

}

void _0RL_cd_40eea1302de063aa_60000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::EZStruct_type&)arg_0 <<= _n;
  (Proxy_Adapter::EZStr_Num&)arg_1 <<= _n;
  (Proxy_Adapter::KeySize&)arg_2 <<= _n;
  arg_3_ = new Proxy_Adapter::EZvalue;
  (Proxy_Adapter::EZvalue&)arg_3_ <<= _n;
  arg_3 = &arg_3_.in();
  (Proxy_Adapter::ResultSize&)arg_4 <<= _n;
  arg_5_ = new Proxy_Adapter::EZvalue;
  (Proxy_Adapter::EZvalue&)arg_5_ <<= _n;
  arg_5 = &arg_5_.inout();

}

void _0RL_cd_40eea1302de063aa_60000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  (const Proxy_Adapter::EZvalue&) *arg_5 >>= _n;

}

void _0RL_cd_40eea1302de063aa_60000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  (Proxy_Adapter::EZvalue&)*arg_5 <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_60000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_60000000* tcd = (_0RL_cd_40eea1302de063aa_60000000*)cd;
  Proxy_Adapter::_impl_StructConf* impl = (Proxy_Adapter::_impl_StructConf*) svnt->_ptrToInterface(Proxy_Adapter::StructConf::_PD_repoId);
  tcd->result = impl->getStructResult(tcd->arg_0, tcd->arg_1, tcd->arg_2, *tcd->arg_3, tcd->arg_4, *tcd->arg_5);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_StructConf::getStructResult(::Proxy_Adapter::EZStruct_type struct_type, ::Proxy_Adapter::EZStr_Num struct_num, ::Proxy_Adapter::KeySize k_length, const ::Proxy_Adapter::EZvalue& key, ::Proxy_Adapter::ResultSize r_length, ::Proxy_Adapter::EZvalue& result)
{
  _0RL_cd_40eea1302de063aa_60000000 _call_desc(_0RL_lcfn_40eea1302de063aa_70000000, "getStructResult", 16);
  _call_desc.arg_0 = struct_type;
  _call_desc.arg_1 = struct_num;
  _call_desc.arg_2 = k_length;
  _call_desc.arg_3 = &(::Proxy_Adapter::EZvalue&) key;
  _call_desc.arg_4 = r_length;
  _call_desc.arg_5 = &(::Proxy_Adapter::EZvalue&) result;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cProxy__Adapter_mEZStruct__type_i_cunsigned_plong_o_cunsigned_plong
class _0RL_cd_40eea1302de063aa_80000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_80000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::EZStruct_type arg_0;
  Proxy_Adapter::EZStr_Num arg_1;
  Proxy_Adapter::uint32 arg_2;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_80000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_40eea1302de063aa_80000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::EZStruct_type&)arg_0 <<= _n;
  (Proxy_Adapter::EZStr_Num&)arg_1 <<= _n;

}

void _0RL_cd_40eea1302de063aa_80000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  arg_2 >>= _n;

}

void _0RL_cd_40eea1302de063aa_80000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  (Proxy_Adapter::uint32&)arg_2 <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_80000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_90000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_80000000* tcd = (_0RL_cd_40eea1302de063aa_80000000*)cd;
  Proxy_Adapter::_impl_StructConf* impl = (Proxy_Adapter::_impl_StructConf*) svnt->_ptrToInterface(Proxy_Adapter::StructConf::_PD_repoId);
  tcd->result = impl->getStructLimit(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_StructConf::getStructLimit(::Proxy_Adapter::EZStruct_type struct_type, ::Proxy_Adapter::EZStr_Num struct_num, ::Proxy_Adapter::uint32& limit)
{
  _0RL_cd_40eea1302de063aa_80000000 _call_desc(_0RL_lcfn_40eea1302de063aa_90000000, "getStructLimit", 15);
  _call_desc.arg_0 = struct_type;
  _call_desc.arg_1 = struct_num;

  _invoke(_call_desc);
  limit = _call_desc.arg_2;
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_a0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_80000000* tcd = (_0RL_cd_40eea1302de063aa_80000000*)cd;
  Proxy_Adapter::_impl_StructConf* impl = (Proxy_Adapter::_impl_StructConf*) svnt->_ptrToInterface(Proxy_Adapter::StructConf::_PD_repoId);
  tcd->result = impl->getStructLength(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_StructConf::getStructLength(::Proxy_Adapter::EZStruct_type struct_type, ::Proxy_Adapter::EZStr_Num struct_num, ::Proxy_Adapter::uint32& length)
{
  _0RL_cd_40eea1302de063aa_80000000 _call_desc(_0RL_lcfn_40eea1302de063aa_a0000000, "getStructLength", 16);
  _call_desc.arg_0 = struct_type;
  _call_desc.arg_1 = struct_num;

  _invoke(_call_desc);
  length = _call_desc.arg_2;
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_b0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_20000000* tcd = (_0RL_cd_40eea1302de063aa_20000000*)cd;
  Proxy_Adapter::_impl_StructConf* impl = (Proxy_Adapter::_impl_StructConf*) svnt->_ptrToInterface(Proxy_Adapter::StructConf::_PD_repoId);
  tcd->result = impl->delStructEntry(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3, *tcd->arg_4, *tcd->arg_5, *tcd->arg_6);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_StructConf::delStructEntry(::Proxy_Adapter::EZStruct_type struct_type, ::Proxy_Adapter::EZStr_Num struct_num, ::Proxy_Adapter::KeySize k_length, ::Proxy_Adapter::ResultSize r_length, const ::Proxy_Adapter::EZvalue& key, const ::Proxy_Adapter::EZvalue& result, const ::Proxy_Adapter::EZvalue& mask)
{
  _0RL_cd_40eea1302de063aa_20000000 _call_desc(_0RL_lcfn_40eea1302de063aa_b0000000, "delStructEntry", 15);
  _call_desc.arg_0 = struct_type;
  _call_desc.arg_1 = struct_num;
  _call_desc.arg_2 = k_length;
  _call_desc.arg_3 = r_length;
  _call_desc.arg_4 = &(::Proxy_Adapter::EZvalue&) key;
  _call_desc.arg_5 = &(::Proxy_Adapter::EZvalue&) result;
  _call_desc.arg_6 = &(::Proxy_Adapter::EZvalue&) mask;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cProxy__Adapter_mEZStruct__type_i_cunsigned_plong
class _0RL_cd_40eea1302de063aa_c0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_c0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::EZStruct_type arg_0;
  Proxy_Adapter::EZStr_Num arg_1;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_c0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_40eea1302de063aa_c0000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::EZStruct_type&)arg_0 <<= _n;
  (Proxy_Adapter::EZStr_Num&)arg_1 <<= _n;

}

void _0RL_cd_40eea1302de063aa_c0000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_40eea1302de063aa_c0000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_c0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_d0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_c0000000* tcd = (_0RL_cd_40eea1302de063aa_c0000000*)cd;
  Proxy_Adapter::_impl_StructConf* impl = (Proxy_Adapter::_impl_StructConf*) svnt->_ptrToInterface(Proxy_Adapter::StructConf::_PD_repoId);
  tcd->result = impl->delStructAllEntries(tcd->arg_0, tcd->arg_1);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_StructConf::delStructAllEntries(::Proxy_Adapter::EZStruct_type struct_type, ::Proxy_Adapter::EZStr_Num struct_num)
{
  _0RL_cd_40eea1302de063aa_c0000000 _call_desc(_0RL_lcfn_40eea1302de063aa_d0000000, "delStructAllEntries", 20);
  _call_desc.arg_0 = struct_type;
  _call_desc.arg_1 = struct_num;

  _invoke(_call_desc);
  return _call_desc.result;


}
Proxy_Adapter::_pof_StructConf::~_pof_StructConf() {}


omniObjRef*
Proxy_Adapter::_pof_StructConf::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::Proxy_Adapter::_objref_StructConf(ior, id);
}


::CORBA::Boolean
Proxy_Adapter::_pof_StructConf::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::Proxy_Adapter::StructConf::_PD_repoId) )
    return 1;
  
  return 0;
}

const Proxy_Adapter::_pof_StructConf _the_pof_Proxy__Adapter_mStructConf;

Proxy_Adapter::_impl_StructConf::~_impl_StructConf() {}


::CORBA::Boolean
Proxy_Adapter::_impl_StructConf::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "testStructConf") ) {

    _0RL_cd_40eea1302de063aa_00000000 _call_desc(_0RL_lcfn_40eea1302de063aa_10000000, "testStructConf", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setStructEntry") ) {

    _0RL_cd_40eea1302de063aa_20000000 _call_desc(_0RL_lcfn_40eea1302de063aa_30000000, "setStructEntry", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getStructEntry") ) {

    _0RL_cd_40eea1302de063aa_40000000 _call_desc(_0RL_lcfn_40eea1302de063aa_50000000, "getStructEntry", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getStructResult") ) {

    _0RL_cd_40eea1302de063aa_60000000 _call_desc(_0RL_lcfn_40eea1302de063aa_70000000, "getStructResult", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getStructLimit") ) {

    _0RL_cd_40eea1302de063aa_80000000 _call_desc(_0RL_lcfn_40eea1302de063aa_90000000, "getStructLimit", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getStructLength") ) {

    _0RL_cd_40eea1302de063aa_80000000 _call_desc(_0RL_lcfn_40eea1302de063aa_a0000000, "getStructLength", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "delStructEntry") ) {

    _0RL_cd_40eea1302de063aa_20000000 _call_desc(_0RL_lcfn_40eea1302de063aa_b0000000, "delStructEntry", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "delStructAllEntries") ) {

    _0RL_cd_40eea1302de063aa_c0000000 _call_desc(_0RL_lcfn_40eea1302de063aa_d0000000, "delStructAllEntries", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
Proxy_Adapter::_impl_StructConf::_ptrToInterface(const char* id)
{
  if( id == ::Proxy_Adapter::StructConf::_PD_repoId )
    return (::Proxy_Adapter::_impl_StructConf*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::Proxy_Adapter::StructConf::_PD_repoId) )
    return (::Proxy_Adapter::_impl_StructConf*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
Proxy_Adapter::_impl_StructConf::_mostDerivedRepoId()
{
  return ::Proxy_Adapter::StructConf::_PD_repoId;
}

Proxy_Adapter::DevMonitor_ptr Proxy_Adapter::DevMonitor_Helper::_nil() {
  return ::Proxy_Adapter::DevMonitor::_nil();
}

::CORBA::Boolean Proxy_Adapter::DevMonitor_Helper::is_nil(::Proxy_Adapter::DevMonitor_ptr p) {
  return ::CORBA::is_nil(p);

}

void Proxy_Adapter::DevMonitor_Helper::release(::Proxy_Adapter::DevMonitor_ptr p) {
  ::CORBA::release(p);
}

void Proxy_Adapter::DevMonitor_Helper::marshalObjRef(::Proxy_Adapter::DevMonitor_ptr obj, cdrStream& s) {
  ::Proxy_Adapter::DevMonitor::_marshalObjRef(obj, s);
}

Proxy_Adapter::DevMonitor_ptr Proxy_Adapter::DevMonitor_Helper::unmarshalObjRef(cdrStream& s) {
  return ::Proxy_Adapter::DevMonitor::_unmarshalObjRef(s);
}

void Proxy_Adapter::DevMonitor_Helper::duplicate(::Proxy_Adapter::DevMonitor_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

Proxy_Adapter::DevMonitor_ptr
Proxy_Adapter::DevMonitor::_duplicate(::Proxy_Adapter::DevMonitor_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

Proxy_Adapter::DevMonitor_ptr
Proxy_Adapter::DevMonitor::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


Proxy_Adapter::DevMonitor_ptr
Proxy_Adapter::DevMonitor::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

Proxy_Adapter::DevMonitor_ptr
Proxy_Adapter::DevMonitor::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_DevMonitor _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_DevMonitor* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_DevMonitor;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* Proxy_Adapter::DevMonitor::_PD_repoId = "IDL:Proxy_Adapter/DevMonitor:1.0";


Proxy_Adapter::_objref_DevMonitor::~_objref_DevMonitor() {
  
}


Proxy_Adapter::_objref_DevMonitor::_objref_DevMonitor(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::Proxy_Adapter::DevMonitor::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
Proxy_Adapter::_objref_DevMonitor::_ptrToObjRef(const char* id)
{
  if( id == ::Proxy_Adapter::DevMonitor::_PD_repoId )
    return (::Proxy_Adapter::DevMonitor_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::Proxy_Adapter::DevMonitor::_PD_repoId) )
    return (::Proxy_Adapter::DevMonitor_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_e0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_00000000* tcd = (_0RL_cd_40eea1302de063aa_00000000*)cd;
  Proxy_Adapter::_impl_DevMonitor* impl = (Proxy_Adapter::_impl_DevMonitor*) svnt->_ptrToInterface(Proxy_Adapter::DevMonitor::_PD_repoId);
  tcd->result = impl->testDevMonitor(*tcd->arg_0);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_DevMonitor::testDevMonitor(::Proxy_Adapter::EZuint& testVal)
{
  _0RL_cd_40eea1302de063aa_00000000 _call_desc(_0RL_lcfn_40eea1302de063aa_e0000000, "testDevMonitor", 15);
  _call_desc.arg_0 = &(::Proxy_Adapter::EZuint&) testVal;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_n_cProxy__Adapter_mEZport
class _0RL_cd_40eea1302de063aa_f0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_f0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::EZport_var arg_0_;
  Proxy_Adapter::EZport* arg_0;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_f0000000::marshalArguments(cdrStream& _n)
{
  (const Proxy_Adapter::EZport&) *arg_0 >>= _n;

}

void _0RL_cd_40eea1302de063aa_f0000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new Proxy_Adapter::EZport;
  (Proxy_Adapter::EZport&)arg_0_ <<= _n;
  arg_0 = &arg_0_.inout();

}

void _0RL_cd_40eea1302de063aa_f0000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  (const Proxy_Adapter::EZport&) *arg_0 >>= _n;

}

void _0RL_cd_40eea1302de063aa_f0000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  (Proxy_Adapter::EZport&)*arg_0 <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_f0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_01000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_f0000000* tcd = (_0RL_cd_40eea1302de063aa_f0000000*)cd;
  Proxy_Adapter::_impl_DevMonitor* impl = (Proxy_Adapter::_impl_DevMonitor*) svnt->_ptrToInterface(Proxy_Adapter::DevMonitor::_PD_repoId);
  tcd->result = impl->getPorts(*tcd->arg_0);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_DevMonitor::getPorts(::Proxy_Adapter::EZport& ports)
{
  _0RL_cd_40eea1302de063aa_f0000000 _call_desc(_0RL_lcfn_40eea1302de063aa_01000000, "getPorts", 9);
  _call_desc.arg_0 = &(::Proxy_Adapter::EZport&) ports;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_o_cboolean
class _0RL_cd_40eea1302de063aa_11000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_11000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::EZuint arg_0;
  Proxy_Adapter::EZPortStatus arg_1;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_11000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_40eea1302de063aa_11000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::EZuint&)arg_0 <<= _n;

}

void _0RL_cd_40eea1302de063aa_11000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  _n.marshalBoolean(arg_1);

}

void _0RL_cd_40eea1302de063aa_11000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  arg_1 = _n.unmarshalBoolean();

}

const char* const _0RL_cd_40eea1302de063aa_11000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_21000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_11000000* tcd = (_0RL_cd_40eea1302de063aa_11000000*)cd;
  Proxy_Adapter::_impl_DevMonitor* impl = (Proxy_Adapter::_impl_DevMonitor*) svnt->_ptrToInterface(Proxy_Adapter::DevMonitor::_PD_repoId);
  tcd->result = impl->getPortStatus(tcd->arg_0, tcd->arg_1);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_DevMonitor::getPortStatus(::Proxy_Adapter::EZuint port_number, ::Proxy_Adapter::EZPortStatus& port_status)
{
  _0RL_cd_40eea1302de063aa_11000000 _call_desc(_0RL_lcfn_40eea1302de063aa_21000000, "getPortStatus", 14);
  _call_desc.arg_0 = port_number;

  _invoke(_call_desc);
  port_status = _call_desc.arg_1;
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_o_cstring
class _0RL_cd_40eea1302de063aa_31000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_31000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::EZuint arg_0;
  ::CORBA::String_var arg_1;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_31000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_40eea1302de063aa_31000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::EZuint&)arg_0 <<= _n;

}

void _0RL_cd_40eea1302de063aa_31000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  _n.marshalString(arg_1,0);

}

void _0RL_cd_40eea1302de063aa_31000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  arg_1 = _n.unmarshalString(0);

}

const char* const _0RL_cd_40eea1302de063aa_31000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_41000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_31000000* tcd = (_0RL_cd_40eea1302de063aa_31000000*)cd;
  Proxy_Adapter::_impl_DevMonitor* impl = (Proxy_Adapter::_impl_DevMonitor*) svnt->_ptrToInterface(Proxy_Adapter::DevMonitor::_PD_repoId);
  tcd->result = impl->getPortName(tcd->arg_0, tcd->arg_1.out());


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_DevMonitor::getPortName(::Proxy_Adapter::EZuint port_number, ::CORBA::String_out port_name)
{
  _0RL_cd_40eea1302de063aa_31000000 _call_desc(_0RL_lcfn_40eea1302de063aa_41000000, "getPortName", 12);
  _call_desc.arg_0 = port_number;

  _invoke(_call_desc);
  port_name = _call_desc.arg_1._retn();
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_n_cProxy__Adapter_mMacAddress
class _0RL_cd_40eea1302de063aa_51000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_51000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::EZuint arg_0;
  Proxy_Adapter::MacAddress_var arg_1_;
  Proxy_Adapter::MacAddress* arg_1;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_51000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  (const Proxy_Adapter::MacAddress&) *arg_1 >>= _n;

}

void _0RL_cd_40eea1302de063aa_51000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::EZuint&)arg_0 <<= _n;
  arg_1_ = new Proxy_Adapter::MacAddress;
  (Proxy_Adapter::MacAddress&)arg_1_ <<= _n;
  arg_1 = &arg_1_.inout();

}

void _0RL_cd_40eea1302de063aa_51000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  (const Proxy_Adapter::MacAddress&) *arg_1 >>= _n;

}

void _0RL_cd_40eea1302de063aa_51000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  (Proxy_Adapter::MacAddress&)*arg_1 <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_51000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_61000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_51000000* tcd = (_0RL_cd_40eea1302de063aa_51000000*)cd;
  Proxy_Adapter::_impl_DevMonitor* impl = (Proxy_Adapter::_impl_DevMonitor*) svnt->_ptrToInterface(Proxy_Adapter::DevMonitor::_PD_repoId);
  tcd->result = impl->getPortMac(tcd->arg_0, *tcd->arg_1);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_DevMonitor::getPortMac(::Proxy_Adapter::EZuint port_number, ::Proxy_Adapter::MacAddress& mac)
{
  _0RL_cd_40eea1302de063aa_51000000 _call_desc(_0RL_lcfn_40eea1302de063aa_61000000, "getPortMac", 11);
  _call_desc.arg_0 = port_number;
  _call_desc.arg_1 = &(::Proxy_Adapter::MacAddress&) mac;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_o_cProxy__Adapter_mEZapiPort__Medium_o_cProxy__Adapter_mEZapiPort__Rate
class _0RL_cd_40eea1302de063aa_71000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_71000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::EZuint arg_0;
  Proxy_Adapter::EZapiPort_Medium arg_1;
  Proxy_Adapter::EZapiPort_Rate arg_2;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_71000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_40eea1302de063aa_71000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::EZuint&)arg_0 <<= _n;

}

void _0RL_cd_40eea1302de063aa_71000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;

}

void _0RL_cd_40eea1302de063aa_71000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  (Proxy_Adapter::EZapiPort_Medium&)arg_1 <<= _n;
  (Proxy_Adapter::EZapiPort_Rate&)arg_2 <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_71000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_81000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_71000000* tcd = (_0RL_cd_40eea1302de063aa_71000000*)cd;
  Proxy_Adapter::_impl_DevMonitor* impl = (Proxy_Adapter::_impl_DevMonitor*) svnt->_ptrToInterface(Proxy_Adapter::DevMonitor::_PD_repoId);
  tcd->result = impl->getPortFeatures(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_DevMonitor::getPortFeatures(::Proxy_Adapter::EZuint port_number, ::Proxy_Adapter::EZapiPort_Medium& medium, ::Proxy_Adapter::EZapiPort_Rate& rate)
{
  _0RL_cd_40eea1302de063aa_71000000 _call_desc(_0RL_lcfn_40eea1302de063aa_81000000, "getPortFeatures", 16);
  _call_desc.arg_0 = port_number;

  _invoke(_call_desc);
  medium = _call_desc.arg_1;
  rate = _call_desc.arg_2;
  return _call_desc.result;


}
Proxy_Adapter::_pof_DevMonitor::~_pof_DevMonitor() {}


omniObjRef*
Proxy_Adapter::_pof_DevMonitor::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::Proxy_Adapter::_objref_DevMonitor(ior, id);
}


::CORBA::Boolean
Proxy_Adapter::_pof_DevMonitor::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::Proxy_Adapter::DevMonitor::_PD_repoId) )
    return 1;
  
  return 0;
}

const Proxy_Adapter::_pof_DevMonitor _the_pof_Proxy__Adapter_mDevMonitor;

Proxy_Adapter::_impl_DevMonitor::~_impl_DevMonitor() {}


::CORBA::Boolean
Proxy_Adapter::_impl_DevMonitor::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "testDevMonitor") ) {

    _0RL_cd_40eea1302de063aa_00000000 _call_desc(_0RL_lcfn_40eea1302de063aa_e0000000, "testDevMonitor", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getPorts") ) {

    _0RL_cd_40eea1302de063aa_f0000000 _call_desc(_0RL_lcfn_40eea1302de063aa_01000000, "getPorts", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getPortStatus") ) {

    _0RL_cd_40eea1302de063aa_11000000 _call_desc(_0RL_lcfn_40eea1302de063aa_21000000, "getPortStatus", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getPortName") ) {

    _0RL_cd_40eea1302de063aa_31000000 _call_desc(_0RL_lcfn_40eea1302de063aa_41000000, "getPortName", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getPortMac") ) {

    _0RL_cd_40eea1302de063aa_51000000 _call_desc(_0RL_lcfn_40eea1302de063aa_61000000, "getPortMac", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getPortFeatures") ) {

    _0RL_cd_40eea1302de063aa_71000000 _call_desc(_0RL_lcfn_40eea1302de063aa_81000000, "getPortFeatures", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
Proxy_Adapter::_impl_DevMonitor::_ptrToInterface(const char* id)
{
  if( id == ::Proxy_Adapter::DevMonitor::_PD_repoId )
    return (::Proxy_Adapter::_impl_DevMonitor*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::Proxy_Adapter::DevMonitor::_PD_repoId) )
    return (::Proxy_Adapter::_impl_DevMonitor*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
Proxy_Adapter::_impl_DevMonitor::_mostDerivedRepoId()
{
  return ::Proxy_Adapter::DevMonitor::_PD_repoId;
}

Proxy_Adapter::TrafficMngt_ptr Proxy_Adapter::TrafficMngt_Helper::_nil() {
  return ::Proxy_Adapter::TrafficMngt::_nil();
}

::CORBA::Boolean Proxy_Adapter::TrafficMngt_Helper::is_nil(::Proxy_Adapter::TrafficMngt_ptr p) {
  return ::CORBA::is_nil(p);

}

void Proxy_Adapter::TrafficMngt_Helper::release(::Proxy_Adapter::TrafficMngt_ptr p) {
  ::CORBA::release(p);
}

void Proxy_Adapter::TrafficMngt_Helper::marshalObjRef(::Proxy_Adapter::TrafficMngt_ptr obj, cdrStream& s) {
  ::Proxy_Adapter::TrafficMngt::_marshalObjRef(obj, s);
}

Proxy_Adapter::TrafficMngt_ptr Proxy_Adapter::TrafficMngt_Helper::unmarshalObjRef(cdrStream& s) {
  return ::Proxy_Adapter::TrafficMngt::_unmarshalObjRef(s);
}

void Proxy_Adapter::TrafficMngt_Helper::duplicate(::Proxy_Adapter::TrafficMngt_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

Proxy_Adapter::TrafficMngt_ptr
Proxy_Adapter::TrafficMngt::_duplicate(::Proxy_Adapter::TrafficMngt_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

Proxy_Adapter::TrafficMngt_ptr
Proxy_Adapter::TrafficMngt::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


Proxy_Adapter::TrafficMngt_ptr
Proxy_Adapter::TrafficMngt::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

Proxy_Adapter::TrafficMngt_ptr
Proxy_Adapter::TrafficMngt::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_TrafficMngt _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_TrafficMngt* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_TrafficMngt;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* Proxy_Adapter::TrafficMngt::_PD_repoId = "IDL:Proxy_Adapter/TrafficMngt:1.0";


Proxy_Adapter::_objref_TrafficMngt::~_objref_TrafficMngt() {
  
}


Proxy_Adapter::_objref_TrafficMngt::_objref_TrafficMngt(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::Proxy_Adapter::TrafficMngt::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
Proxy_Adapter::_objref_TrafficMngt::_ptrToObjRef(const char* id)
{
  if( id == ::Proxy_Adapter::TrafficMngt::_PD_repoId )
    return (::Proxy_Adapter::TrafficMngt_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::Proxy_Adapter::TrafficMngt::_PD_repoId) )
    return (::Proxy_Adapter::TrafficMngt_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_91000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_00000000* tcd = (_0RL_cd_40eea1302de063aa_00000000*)cd;
  Proxy_Adapter::_impl_TrafficMngt* impl = (Proxy_Adapter::_impl_TrafficMngt*) svnt->_ptrToInterface(Proxy_Adapter::TrafficMngt::_PD_repoId);
  tcd->result = impl->testTrafficMngt(*tcd->arg_0);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_TrafficMngt::testTrafficMngt(::Proxy_Adapter::EZuint& testVal)
{
  _0RL_cd_40eea1302de063aa_00000000 _call_desc(_0RL_lcfn_40eea1302de063aa_91000000, "testTrafficMngt", 16);
  _call_desc.arg_0 = &(::Proxy_Adapter::EZuint&) testVal;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_i_cunsigned_plong_i_cunsigned_plong_i_cProxy__Adapter_mEZapiTM__ShapingLevel_i_cProxy__Adapter_mEZapiTM__type
class _0RL_cd_40eea1302de063aa_a1000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_a1000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::uint32 arg_0;
  Proxy_Adapter::uint32 arg_1;
  Proxy_Adapter::uint32 arg_2;
  Proxy_Adapter::EZapiTM_ShapingLevel arg_3;
  Proxy_Adapter::EZapiTM_type arg_4;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_a1000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;
  arg_3 >>= _n;
  arg_4 >>= _n;

}

void _0RL_cd_40eea1302de063aa_a1000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::uint32&)arg_0 <<= _n;
  (Proxy_Adapter::uint32&)arg_1 <<= _n;
  (Proxy_Adapter::uint32&)arg_2 <<= _n;
  (Proxy_Adapter::EZapiTM_ShapingLevel&)arg_3 <<= _n;
  (Proxy_Adapter::EZapiTM_type&)arg_4 <<= _n;

}

void _0RL_cd_40eea1302de063aa_a1000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_40eea1302de063aa_a1000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_a1000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_b1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_a1000000* tcd = (_0RL_cd_40eea1302de063aa_a1000000*)cd;
  Proxy_Adapter::_impl_TrafficMngt* impl = (Proxy_Adapter::_impl_TrafficMngt*) svnt->_ptrToInterface(Proxy_Adapter::TrafficMngt::_PD_repoId);
  tcd->result = impl->tmSetShapingProfile(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3, tcd->arg_4);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_TrafficMngt::tmSetShapingProfile(::Proxy_Adapter::uint32 profile, ::Proxy_Adapter::uint32 cir, ::Proxy_Adapter::uint32 cbs, ::Proxy_Adapter::EZapiTM_ShapingLevel level, ::Proxy_Adapter::EZapiTM_type tm)
{
  _0RL_cd_40eea1302de063aa_a1000000 _call_desc(_0RL_lcfn_40eea1302de063aa_b1000000, "tmSetShapingProfile", 20);
  _call_desc.arg_0 = profile;
  _call_desc.arg_1 = cir;
  _call_desc.arg_2 = cbs;
  _call_desc.arg_3 = level;
  _call_desc.arg_4 = tm;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_o_cunsigned_plong_o_cunsigned_plong_i_cProxy__Adapter_mEZapiTM__ShapingLevel_i_cProxy__Adapter_mEZapiTM__type
class _0RL_cd_40eea1302de063aa_c1000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_c1000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::uint32 arg_0;
  Proxy_Adapter::uint32 arg_1;
  Proxy_Adapter::uint32 arg_2;
  Proxy_Adapter::EZapiTM_ShapingLevel arg_3;
  Proxy_Adapter::EZapiTM_type arg_4;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_c1000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_3 >>= _n;
  arg_4 >>= _n;

}

void _0RL_cd_40eea1302de063aa_c1000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::uint32&)arg_0 <<= _n;
  (Proxy_Adapter::EZapiTM_ShapingLevel&)arg_3 <<= _n;
  (Proxy_Adapter::EZapiTM_type&)arg_4 <<= _n;

}

void _0RL_cd_40eea1302de063aa_c1000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;

}

void _0RL_cd_40eea1302de063aa_c1000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  (Proxy_Adapter::uint32&)arg_1 <<= _n;
  (Proxy_Adapter::uint32&)arg_2 <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_c1000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_d1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_c1000000* tcd = (_0RL_cd_40eea1302de063aa_c1000000*)cd;
  Proxy_Adapter::_impl_TrafficMngt* impl = (Proxy_Adapter::_impl_TrafficMngt*) svnt->_ptrToInterface(Proxy_Adapter::TrafficMngt::_PD_repoId);
  tcd->result = impl->tmGetShapingProfile(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3, tcd->arg_4);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_TrafficMngt::tmGetShapingProfile(::Proxy_Adapter::uint32 profile, ::Proxy_Adapter::uint32& cir, ::Proxy_Adapter::uint32& cbs, ::Proxy_Adapter::EZapiTM_ShapingLevel level, ::Proxy_Adapter::EZapiTM_type tm)
{
  _0RL_cd_40eea1302de063aa_c1000000 _call_desc(_0RL_lcfn_40eea1302de063aa_d1000000, "tmGetShapingProfile", 20);
  _call_desc.arg_0 = profile;
  _call_desc.arg_3 = level;
  _call_desc.arg_4 = tm;

  _invoke(_call_desc);
  cir = _call_desc.arg_1;
  cbs = _call_desc.arg_2;
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_i_cunsigned_plong_i_cunsigned_plong_i_cProxy__Adapter_mEZapiTM__Priority_i_cunsigned_plong_i_cProxy__Adapter_mEZapiTM__Entity_i_cProxy__Adapter_mEZapiTM__Shaping_i_cProxy__Adapter_mEZapiTM__type
class _0RL_cd_40eea1302de063aa_e1000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_e1000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::uint32 arg_0;
  Proxy_Adapter::uint32 arg_1;
  Proxy_Adapter::uint32 arg_2;
  Proxy_Adapter::EZapiTM_Priority arg_3;
  Proxy_Adapter::uint32 arg_4;
  Proxy_Adapter::EZapiTM_Entity arg_5;
  Proxy_Adapter::EZapiTM_Shaping arg_6;
  Proxy_Adapter::EZapiTM_type arg_7;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_e1000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;
  arg_3 >>= _n;
  arg_4 >>= _n;
  arg_5 >>= _n;
  arg_6 >>= _n;
  arg_7 >>= _n;

}

void _0RL_cd_40eea1302de063aa_e1000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::uint32&)arg_0 <<= _n;
  (Proxy_Adapter::uint32&)arg_1 <<= _n;
  (Proxy_Adapter::uint32&)arg_2 <<= _n;
  (Proxy_Adapter::EZapiTM_Priority&)arg_3 <<= _n;
  (Proxy_Adapter::uint32&)arg_4 <<= _n;
  (Proxy_Adapter::EZapiTM_Entity&)arg_5 <<= _n;
  (Proxy_Adapter::EZapiTM_Shaping&)arg_6 <<= _n;
  (Proxy_Adapter::EZapiTM_type&)arg_7 <<= _n;

}

void _0RL_cd_40eea1302de063aa_e1000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_40eea1302de063aa_e1000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_e1000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_f1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_e1000000* tcd = (_0RL_cd_40eea1302de063aa_e1000000*)cd;
  Proxy_Adapter::_impl_TrafficMngt* impl = (Proxy_Adapter::_impl_TrafficMngt*) svnt->_ptrToInterface(Proxy_Adapter::TrafficMngt::_PD_repoId);
  tcd->result = impl->tmSetEntity(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3, tcd->arg_4, tcd->arg_5, tcd->arg_6, tcd->arg_7);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_TrafficMngt::tmSetEntity(::Proxy_Adapter::uint32 shaping_profile, ::Proxy_Adapter::uint32 wred_profile, ::Proxy_Adapter::uint32 wfq_profile, ::Proxy_Adapter::EZapiTM_Priority priority, ::Proxy_Adapter::uint32 entity, ::Proxy_Adapter::EZapiTM_Entity level, ::Proxy_Adapter::EZapiTM_Shaping mode, ::Proxy_Adapter::EZapiTM_type tm)
{
  _0RL_cd_40eea1302de063aa_e1000000 _call_desc(_0RL_lcfn_40eea1302de063aa_f1000000, "tmSetEntity", 12);
  _call_desc.arg_0 = shaping_profile;
  _call_desc.arg_1 = wred_profile;
  _call_desc.arg_2 = wfq_profile;
  _call_desc.arg_3 = priority;
  _call_desc.arg_4 = entity;
  _call_desc.arg_5 = level;
  _call_desc.arg_6 = mode;
  _call_desc.arg_7 = tm;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_o_cunsigned_plong_o_cunsigned_plong_o_cunsigned_plong_o_cProxy__Adapter_mEZapiTM__Priority_i_cunsigned_plong_i_cProxy__Adapter_mEZapiTM__Entity_o_cProxy__Adapter_mEZapiTM__Shaping_i_cProxy__Adapter_mEZapiTM__type
class _0RL_cd_40eea1302de063aa_02000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_02000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::uint32 arg_0;
  Proxy_Adapter::uint32 arg_1;
  Proxy_Adapter::uint32 arg_2;
  Proxy_Adapter::EZapiTM_Priority arg_3;
  Proxy_Adapter::uint32 arg_4;
  Proxy_Adapter::EZapiTM_Entity arg_5;
  Proxy_Adapter::EZapiTM_Shaping arg_6;
  Proxy_Adapter::EZapiTM_type arg_7;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_02000000::marshalArguments(cdrStream& _n)
{
  arg_4 >>= _n;
  arg_5 >>= _n;
  arg_7 >>= _n;

}

void _0RL_cd_40eea1302de063aa_02000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::uint32&)arg_4 <<= _n;
  (Proxy_Adapter::EZapiTM_Entity&)arg_5 <<= _n;
  (Proxy_Adapter::EZapiTM_type&)arg_7 <<= _n;

}

void _0RL_cd_40eea1302de063aa_02000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;
  arg_3 >>= _n;
  arg_6 >>= _n;

}

void _0RL_cd_40eea1302de063aa_02000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  (Proxy_Adapter::uint32&)arg_0 <<= _n;
  (Proxy_Adapter::uint32&)arg_1 <<= _n;
  (Proxy_Adapter::uint32&)arg_2 <<= _n;
  (Proxy_Adapter::EZapiTM_Priority&)arg_3 <<= _n;
  (Proxy_Adapter::EZapiTM_Shaping&)arg_6 <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_02000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_12000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_02000000* tcd = (_0RL_cd_40eea1302de063aa_02000000*)cd;
  Proxy_Adapter::_impl_TrafficMngt* impl = (Proxy_Adapter::_impl_TrafficMngt*) svnt->_ptrToInterface(Proxy_Adapter::TrafficMngt::_PD_repoId);
  tcd->result = impl->tmGetEntity(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3, tcd->arg_4, tcd->arg_5, tcd->arg_6, tcd->arg_7);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_TrafficMngt::tmGetEntity(::Proxy_Adapter::uint32& shaping_profile, ::Proxy_Adapter::uint32& wred_profile, ::Proxy_Adapter::uint32& wfq_profile, ::Proxy_Adapter::EZapiTM_Priority& priority, ::Proxy_Adapter::uint32 entity, ::Proxy_Adapter::EZapiTM_Entity level, ::Proxy_Adapter::EZapiTM_Shaping& mode, ::Proxy_Adapter::EZapiTM_type tm)
{
  _0RL_cd_40eea1302de063aa_02000000 _call_desc(_0RL_lcfn_40eea1302de063aa_12000000, "tmGetEntity", 12);
  _call_desc.arg_4 = entity;
  _call_desc.arg_5 = level;
  _call_desc.arg_7 = tm;

  _invoke(_call_desc);
  shaping_profile = _call_desc.arg_0;
  wred_profile = _call_desc.arg_1;
  wfq_profile = _call_desc.arg_2;
  priority = _call_desc.arg_3;
  mode = _call_desc.arg_6;
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_i_cunsigned_plong_i_cProxy__Adapter_mEZapiTM__WFQLevel_i_cProxy__Adapter_mEZapiTM__type
class _0RL_cd_40eea1302de063aa_22000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_22000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::uint32 arg_0;
  Proxy_Adapter::uint32 arg_1;
  Proxy_Adapter::EZapiTM_WFQLevel arg_2;
  Proxy_Adapter::EZapiTM_type arg_3;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_22000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;
  arg_3 >>= _n;

}

void _0RL_cd_40eea1302de063aa_22000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::uint32&)arg_0 <<= _n;
  (Proxy_Adapter::uint32&)arg_1 <<= _n;
  (Proxy_Adapter::EZapiTM_WFQLevel&)arg_2 <<= _n;
  (Proxy_Adapter::EZapiTM_type&)arg_3 <<= _n;

}

void _0RL_cd_40eea1302de063aa_22000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_40eea1302de063aa_22000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_22000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_32000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_22000000* tcd = (_0RL_cd_40eea1302de063aa_22000000*)cd;
  Proxy_Adapter::_impl_TrafficMngt* impl = (Proxy_Adapter::_impl_TrafficMngt*) svnt->_ptrToInterface(Proxy_Adapter::TrafficMngt::_PD_repoId);
  tcd->result = impl->tmSetWfqProfile(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_TrafficMngt::tmSetWfqProfile(::Proxy_Adapter::uint32 profile, ::Proxy_Adapter::uint32 weight, ::Proxy_Adapter::EZapiTM_WFQLevel level, ::Proxy_Adapter::EZapiTM_type tm)
{
  _0RL_cd_40eea1302de063aa_22000000 _call_desc(_0RL_lcfn_40eea1302de063aa_32000000, "tmSetWfqProfile", 16);
  _call_desc.arg_0 = profile;
  _call_desc.arg_1 = weight;
  _call_desc.arg_2 = level;
  _call_desc.arg_3 = tm;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_o_cunsigned_plong_i_cProxy__Adapter_mEZapiTM__WFQLevel_i_cProxy__Adapter_mEZapiTM__type
class _0RL_cd_40eea1302de063aa_42000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_42000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::uint32 arg_0;
  Proxy_Adapter::uint32 arg_1;
  Proxy_Adapter::EZapiTM_WFQLevel arg_2;
  Proxy_Adapter::EZapiTM_type arg_3;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_42000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_2 >>= _n;
  arg_3 >>= _n;

}

void _0RL_cd_40eea1302de063aa_42000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::uint32&)arg_0 <<= _n;
  (Proxy_Adapter::EZapiTM_WFQLevel&)arg_2 <<= _n;
  (Proxy_Adapter::EZapiTM_type&)arg_3 <<= _n;

}

void _0RL_cd_40eea1302de063aa_42000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_40eea1302de063aa_42000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  (Proxy_Adapter::uint32&)arg_1 <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_42000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_52000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_42000000* tcd = (_0RL_cd_40eea1302de063aa_42000000*)cd;
  Proxy_Adapter::_impl_TrafficMngt* impl = (Proxy_Adapter::_impl_TrafficMngt*) svnt->_ptrToInterface(Proxy_Adapter::TrafficMngt::_PD_repoId);
  tcd->result = impl->tmGetWfqProfile(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_TrafficMngt::tmGetWfqProfile(::Proxy_Adapter::uint32 profile, ::Proxy_Adapter::uint32& weight, ::Proxy_Adapter::EZapiTM_WFQLevel level, ::Proxy_Adapter::EZapiTM_type tm)
{
  _0RL_cd_40eea1302de063aa_42000000 _call_desc(_0RL_lcfn_40eea1302de063aa_52000000, "tmGetWfqProfile", 16);
  _call_desc.arg_0 = profile;
  _call_desc.arg_2 = level;
  _call_desc.arg_3 = tm;

  _invoke(_call_desc);
  weight = _call_desc.arg_1;
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_i_cunsigned_plong_i_cProxy__Adapter_mEZapiTM__WREDLevel_i_cProxy__Adapter_mEZapiTM__type
class _0RL_cd_40eea1302de063aa_62000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_62000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::uint32 arg_0;
  Proxy_Adapter::uint32 arg_1;
  Proxy_Adapter::EZapiTM_WREDLevel arg_2;
  Proxy_Adapter::EZapiTM_type arg_3;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_62000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;
  arg_3 >>= _n;

}

void _0RL_cd_40eea1302de063aa_62000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::uint32&)arg_0 <<= _n;
  (Proxy_Adapter::uint32&)arg_1 <<= _n;
  (Proxy_Adapter::EZapiTM_WREDLevel&)arg_2 <<= _n;
  (Proxy_Adapter::EZapiTM_type&)arg_3 <<= _n;

}

void _0RL_cd_40eea1302de063aa_62000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_40eea1302de063aa_62000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_62000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_72000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_62000000* tcd = (_0RL_cd_40eea1302de063aa_62000000*)cd;
  Proxy_Adapter::_impl_TrafficMngt* impl = (Proxy_Adapter::_impl_TrafficMngt*) svnt->_ptrToInterface(Proxy_Adapter::TrafficMngt::_PD_repoId);
  tcd->result = impl->tmSetWredProfile(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_TrafficMngt::tmSetWredProfile(::Proxy_Adapter::uint32 profile, ::Proxy_Adapter::uint32 guaranteedThresh, ::Proxy_Adapter::EZapiTM_WREDLevel level, ::Proxy_Adapter::EZapiTM_type tm)
{
  _0RL_cd_40eea1302de063aa_62000000 _call_desc(_0RL_lcfn_40eea1302de063aa_72000000, "tmSetWredProfile", 17);
  _call_desc.arg_0 = profile;
  _call_desc.arg_1 = guaranteedThresh;
  _call_desc.arg_2 = level;
  _call_desc.arg_3 = tm;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_o_cunsigned_plong_i_cProxy__Adapter_mEZapiTM__WREDLevel_i_cProxy__Adapter_mEZapiTM__type
class _0RL_cd_40eea1302de063aa_82000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_82000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::uint32 arg_0;
  Proxy_Adapter::uint32 arg_1;
  Proxy_Adapter::EZapiTM_WREDLevel arg_2;
  Proxy_Adapter::EZapiTM_type arg_3;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_82000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_2 >>= _n;
  arg_3 >>= _n;

}

void _0RL_cd_40eea1302de063aa_82000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::uint32&)arg_0 <<= _n;
  (Proxy_Adapter::EZapiTM_WREDLevel&)arg_2 <<= _n;
  (Proxy_Adapter::EZapiTM_type&)arg_3 <<= _n;

}

void _0RL_cd_40eea1302de063aa_82000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_40eea1302de063aa_82000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  (Proxy_Adapter::uint32&)arg_1 <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_82000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_92000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_82000000* tcd = (_0RL_cd_40eea1302de063aa_82000000*)cd;
  Proxy_Adapter::_impl_TrafficMngt* impl = (Proxy_Adapter::_impl_TrafficMngt*) svnt->_ptrToInterface(Proxy_Adapter::TrafficMngt::_PD_repoId);
  tcd->result = impl->tmGetWredProfile(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_TrafficMngt::tmGetWredProfile(::Proxy_Adapter::uint32 profile, ::Proxy_Adapter::uint32& guaranteedThresh, ::Proxy_Adapter::EZapiTM_WREDLevel level, ::Proxy_Adapter::EZapiTM_type tm)
{
  _0RL_cd_40eea1302de063aa_82000000 _call_desc(_0RL_lcfn_40eea1302de063aa_92000000, "tmGetWredProfile", 17);
  _call_desc.arg_0 = profile;
  _call_desc.arg_2 = level;
  _call_desc.arg_3 = tm;

  _invoke(_call_desc);
  guaranteedThresh = _call_desc.arg_1;
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_i_cunsigned_plong_i_cunsigned_plong
class _0RL_cd_40eea1302de063aa_a2000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_a2000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::uint32 arg_0;
  Proxy_Adapter::uint32 arg_1;
  Proxy_Adapter::uint32 arg_2;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_a2000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;

}

void _0RL_cd_40eea1302de063aa_a2000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::uint32&)arg_0 <<= _n;
  (Proxy_Adapter::uint32&)arg_1 <<= _n;
  (Proxy_Adapter::uint32&)arg_2 <<= _n;

}

void _0RL_cd_40eea1302de063aa_a2000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_40eea1302de063aa_a2000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_a2000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_b2000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_a2000000* tcd = (_0RL_cd_40eea1302de063aa_a2000000*)cd;
  Proxy_Adapter::_impl_TrafficMngt* impl = (Proxy_Adapter::_impl_TrafficMngt*) svnt->_ptrToInterface(Proxy_Adapter::TrafficMngt::_PD_repoId);
  tcd->result = impl->setTokenbucketProfile(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_TrafficMngt::setTokenbucketProfile(::Proxy_Adapter::uint32 profil_num, ::Proxy_Adapter::uint32 cir, ::Proxy_Adapter::uint32 cbs)
{
  _0RL_cd_40eea1302de063aa_a2000000 _call_desc(_0RL_lcfn_40eea1302de063aa_b2000000, "setTokenbucketProfile", 22);
  _call_desc.arg_0 = profil_num;
  _call_desc.arg_1 = cir;
  _call_desc.arg_2 = cbs;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_i_cunsigned_plong
class _0RL_cd_40eea1302de063aa_c2000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_c2000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::uint32 arg_0;
  Proxy_Adapter::uint32 arg_1;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_c2000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_40eea1302de063aa_c2000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::uint32&)arg_0 <<= _n;
  (Proxy_Adapter::uint32&)arg_1 <<= _n;

}

void _0RL_cd_40eea1302de063aa_c2000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_40eea1302de063aa_c2000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_c2000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_d2000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_c2000000* tcd = (_0RL_cd_40eea1302de063aa_c2000000*)cd;
  Proxy_Adapter::_impl_TrafficMngt* impl = (Proxy_Adapter::_impl_TrafficMngt*) svnt->_ptrToInterface(Proxy_Adapter::TrafficMngt::_PD_repoId);
  tcd->result = impl->setTokenbucketCounter(tcd->arg_0, tcd->arg_1);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_TrafficMngt::setTokenbucketCounter(::Proxy_Adapter::uint32 counter_num, ::Proxy_Adapter::uint32 tb_profile)
{
  _0RL_cd_40eea1302de063aa_c2000000 _call_desc(_0RL_lcfn_40eea1302de063aa_d2000000, "setTokenbucketCounter", 22);
  _call_desc.arg_0 = counter_num;
  _call_desc.arg_1 = tb_profile;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_o_cunsigned_plong_o_cunsigned_plong
class _0RL_cd_40eea1302de063aa_e2000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_e2000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::uint32 arg_0;
  Proxy_Adapter::uint32 arg_1;
  Proxy_Adapter::uint32 arg_2;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_e2000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_40eea1302de063aa_e2000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::uint32&)arg_0 <<= _n;

}

void _0RL_cd_40eea1302de063aa_e2000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;

}

void _0RL_cd_40eea1302de063aa_e2000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  (Proxy_Adapter::uint32&)arg_1 <<= _n;
  (Proxy_Adapter::uint32&)arg_2 <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_e2000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_f2000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_e2000000* tcd = (_0RL_cd_40eea1302de063aa_e2000000*)cd;
  Proxy_Adapter::_impl_TrafficMngt* impl = (Proxy_Adapter::_impl_TrafficMngt*) svnt->_ptrToInterface(Proxy_Adapter::TrafficMngt::_PD_repoId);
  tcd->result = impl->getTokenbucketProfile(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_TrafficMngt::getTokenbucketProfile(::Proxy_Adapter::uint32 profil_num, ::Proxy_Adapter::uint32& cir, ::Proxy_Adapter::uint32& cbs)
{
  _0RL_cd_40eea1302de063aa_e2000000 _call_desc(_0RL_lcfn_40eea1302de063aa_f2000000, "getTokenbucketProfile", 22);
  _call_desc.arg_0 = profil_num;

  _invoke(_call_desc);
  cir = _call_desc.arg_1;
  cbs = _call_desc.arg_2;
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_o_cunsigned_plong
class _0RL_cd_40eea1302de063aa_03000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_03000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::uint32 arg_0;
  Proxy_Adapter::uint32 arg_1;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_03000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_40eea1302de063aa_03000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::uint32&)arg_0 <<= _n;

}

void _0RL_cd_40eea1302de063aa_03000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_40eea1302de063aa_03000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  (Proxy_Adapter::uint32&)arg_1 <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_03000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_13000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_03000000* tcd = (_0RL_cd_40eea1302de063aa_03000000*)cd;
  Proxy_Adapter::_impl_TrafficMngt* impl = (Proxy_Adapter::_impl_TrafficMngt*) svnt->_ptrToInterface(Proxy_Adapter::TrafficMngt::_PD_repoId);
  tcd->result = impl->getTokenbucketCounter(tcd->arg_0, tcd->arg_1);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_TrafficMngt::getTokenbucketCounter(::Proxy_Adapter::uint32 counter_num, ::Proxy_Adapter::uint32& tb_profile)
{
  _0RL_cd_40eea1302de063aa_03000000 _call_desc(_0RL_lcfn_40eea1302de063aa_13000000, "getTokenbucketCounter", 22);
  _call_desc.arg_0 = counter_num;

  _invoke(_call_desc);
  tb_profile = _call_desc.arg_1;
  return _call_desc.result;


}
Proxy_Adapter::_pof_TrafficMngt::~_pof_TrafficMngt() {}


omniObjRef*
Proxy_Adapter::_pof_TrafficMngt::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::Proxy_Adapter::_objref_TrafficMngt(ior, id);
}


::CORBA::Boolean
Proxy_Adapter::_pof_TrafficMngt::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::Proxy_Adapter::TrafficMngt::_PD_repoId) )
    return 1;
  
  return 0;
}

const Proxy_Adapter::_pof_TrafficMngt _the_pof_Proxy__Adapter_mTrafficMngt;

Proxy_Adapter::_impl_TrafficMngt::~_impl_TrafficMngt() {}


::CORBA::Boolean
Proxy_Adapter::_impl_TrafficMngt::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "testTrafficMngt") ) {

    _0RL_cd_40eea1302de063aa_00000000 _call_desc(_0RL_lcfn_40eea1302de063aa_91000000, "testTrafficMngt", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "tmSetShapingProfile") ) {

    _0RL_cd_40eea1302de063aa_a1000000 _call_desc(_0RL_lcfn_40eea1302de063aa_b1000000, "tmSetShapingProfile", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "tmGetShapingProfile") ) {

    _0RL_cd_40eea1302de063aa_c1000000 _call_desc(_0RL_lcfn_40eea1302de063aa_d1000000, "tmGetShapingProfile", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "tmSetEntity") ) {

    _0RL_cd_40eea1302de063aa_e1000000 _call_desc(_0RL_lcfn_40eea1302de063aa_f1000000, "tmSetEntity", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "tmGetEntity") ) {

    _0RL_cd_40eea1302de063aa_02000000 _call_desc(_0RL_lcfn_40eea1302de063aa_12000000, "tmGetEntity", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "tmSetWfqProfile") ) {

    _0RL_cd_40eea1302de063aa_22000000 _call_desc(_0RL_lcfn_40eea1302de063aa_32000000, "tmSetWfqProfile", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "tmGetWfqProfile") ) {

    _0RL_cd_40eea1302de063aa_42000000 _call_desc(_0RL_lcfn_40eea1302de063aa_52000000, "tmGetWfqProfile", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "tmSetWredProfile") ) {

    _0RL_cd_40eea1302de063aa_62000000 _call_desc(_0RL_lcfn_40eea1302de063aa_72000000, "tmSetWredProfile", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "tmGetWredProfile") ) {

    _0RL_cd_40eea1302de063aa_82000000 _call_desc(_0RL_lcfn_40eea1302de063aa_92000000, "tmGetWredProfile", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setTokenbucketProfile") ) {

    _0RL_cd_40eea1302de063aa_a2000000 _call_desc(_0RL_lcfn_40eea1302de063aa_b2000000, "setTokenbucketProfile", 22, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setTokenbucketCounter") ) {

    _0RL_cd_40eea1302de063aa_c2000000 _call_desc(_0RL_lcfn_40eea1302de063aa_d2000000, "setTokenbucketCounter", 22, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getTokenbucketProfile") ) {

    _0RL_cd_40eea1302de063aa_e2000000 _call_desc(_0RL_lcfn_40eea1302de063aa_f2000000, "getTokenbucketProfile", 22, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getTokenbucketCounter") ) {

    _0RL_cd_40eea1302de063aa_03000000 _call_desc(_0RL_lcfn_40eea1302de063aa_13000000, "getTokenbucketCounter", 22, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
Proxy_Adapter::_impl_TrafficMngt::_ptrToInterface(const char* id)
{
  if( id == ::Proxy_Adapter::TrafficMngt::_PD_repoId )
    return (::Proxy_Adapter::_impl_TrafficMngt*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::Proxy_Adapter::TrafficMngt::_PD_repoId) )
    return (::Proxy_Adapter::_impl_TrafficMngt*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
Proxy_Adapter::_impl_TrafficMngt::_mostDerivedRepoId()
{
  return ::Proxy_Adapter::TrafficMngt::_PD_repoId;
}

Proxy_Adapter::NP3FrameHandl_ptr Proxy_Adapter::NP3FrameHandl_Helper::_nil() {
  return ::Proxy_Adapter::NP3FrameHandl::_nil();
}

::CORBA::Boolean Proxy_Adapter::NP3FrameHandl_Helper::is_nil(::Proxy_Adapter::NP3FrameHandl_ptr p) {
  return ::CORBA::is_nil(p);

}

void Proxy_Adapter::NP3FrameHandl_Helper::release(::Proxy_Adapter::NP3FrameHandl_ptr p) {
  ::CORBA::release(p);
}

void Proxy_Adapter::NP3FrameHandl_Helper::marshalObjRef(::Proxy_Adapter::NP3FrameHandl_ptr obj, cdrStream& s) {
  ::Proxy_Adapter::NP3FrameHandl::_marshalObjRef(obj, s);
}

Proxy_Adapter::NP3FrameHandl_ptr Proxy_Adapter::NP3FrameHandl_Helper::unmarshalObjRef(cdrStream& s) {
  return ::Proxy_Adapter::NP3FrameHandl::_unmarshalObjRef(s);
}

void Proxy_Adapter::NP3FrameHandl_Helper::duplicate(::Proxy_Adapter::NP3FrameHandl_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

Proxy_Adapter::NP3FrameHandl_ptr
Proxy_Adapter::NP3FrameHandl::_duplicate(::Proxy_Adapter::NP3FrameHandl_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

Proxy_Adapter::NP3FrameHandl_ptr
Proxy_Adapter::NP3FrameHandl::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


Proxy_Adapter::NP3FrameHandl_ptr
Proxy_Adapter::NP3FrameHandl::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

Proxy_Adapter::NP3FrameHandl_ptr
Proxy_Adapter::NP3FrameHandl::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_NP3FrameHandl _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_NP3FrameHandl* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_NP3FrameHandl;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* Proxy_Adapter::NP3FrameHandl::_PD_repoId = "IDL:Proxy_Adapter/NP3FrameHandl:1.0";


Proxy_Adapter::_objref_NP3FrameHandl::~_objref_NP3FrameHandl() {
  
}


Proxy_Adapter::_objref_NP3FrameHandl::_objref_NP3FrameHandl(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::Proxy_Adapter::NP3FrameHandl::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
Proxy_Adapter::_objref_NP3FrameHandl::_ptrToObjRef(const char* id)
{
  if( id == ::Proxy_Adapter::NP3FrameHandl::_PD_repoId )
    return (::Proxy_Adapter::NP3FrameHandl_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::Proxy_Adapter::NP3FrameHandl::_PD_repoId) )
    return (::Proxy_Adapter::NP3FrameHandl_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_23000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_00000000* tcd = (_0RL_cd_40eea1302de063aa_00000000*)cd;
  Proxy_Adapter::_impl_NP3FrameHandl* impl = (Proxy_Adapter::_impl_NP3FrameHandl*) svnt->_ptrToInterface(Proxy_Adapter::NP3FrameHandl::_PD_repoId);
  tcd->result = impl->testNP3FrameHandl(*tcd->arg_0);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_NP3FrameHandl::testNP3FrameHandl(::Proxy_Adapter::EZuint& testVal)
{
  _0RL_cd_40eea1302de063aa_00000000 _call_desc(_0RL_lcfn_40eea1302de063aa_23000000, "testNP3FrameHandl", 18);
  _call_desc.arg_0 = &(::Proxy_Adapter::EZuint&) testVal;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_i_cunsigned_plong_i_cunsigned_plong_i_cProxy__Adapter_mEZapiFrame__BufferRegion_i_cProxy__Adapter_mEZapiFrame__TransmitQ_i_cProxy__Adapter_mEZvalue_i_cunsigned_plong
class _0RL_cd_40eea1302de063aa_33000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_33000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::uint32 arg_0;
  Proxy_Adapter::uint32 arg_1;
  Proxy_Adapter::EZapiFrame_BufferRegion arg_2;
  Proxy_Adapter::EZapiFrame_TransmitQ arg_3;
  Proxy_Adapter::EZvalue_var arg_4_;
  const Proxy_Adapter::EZvalue* arg_4;
  Proxy_Adapter::uint32 arg_5;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_33000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;
  arg_3 >>= _n;
  (const Proxy_Adapter::EZvalue&) *arg_4 >>= _n;
  arg_5 >>= _n;

}

void _0RL_cd_40eea1302de063aa_33000000::unmarshalArguments(cdrStream& _n)
{
  (Proxy_Adapter::uint32&)arg_0 <<= _n;
  (Proxy_Adapter::uint32&)arg_1 <<= _n;
  (Proxy_Adapter::EZapiFrame_BufferRegion&)arg_2 <<= _n;
  (Proxy_Adapter::EZapiFrame_TransmitQ&)arg_3 <<= _n;
  arg_4_ = new Proxy_Adapter::EZvalue;
  (Proxy_Adapter::EZvalue&)arg_4_ <<= _n;
  arg_4 = &arg_4_.in();
  (Proxy_Adapter::uint32&)arg_5 <<= _n;

}

void _0RL_cd_40eea1302de063aa_33000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_40eea1302de063aa_33000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_33000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_43000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_33000000* tcd = (_0RL_cd_40eea1302de063aa_33000000*)cd;
  Proxy_Adapter::_impl_NP3FrameHandl* impl = (Proxy_Adapter::_impl_NP3FrameHandl*) svnt->_ptrToInterface(Proxy_Adapter::NP3FrameHandl::_PD_repoId);
  tcd->result = impl->frameSend(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3, *tcd->arg_4, tcd->arg_5);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_NP3FrameHandl::frameSend(::Proxy_Adapter::uint32 destination_port, ::Proxy_Adapter::uint32 uqTMFlowId, ::Proxy_Adapter::EZapiFrame_BufferRegion buffor_region, ::Proxy_Adapter::EZapiFrame_TransmitQ transmisions_direction, const ::Proxy_Adapter::EZvalue& frame_data, ::Proxy_Adapter::uint32 frame_length)
{
  _0RL_cd_40eea1302de063aa_33000000 _call_desc(_0RL_lcfn_40eea1302de063aa_43000000, "frameSend", 10);
  _call_desc.arg_0 = destination_port;
  _call_desc.arg_1 = uqTMFlowId;
  _call_desc.arg_2 = buffor_region;
  _call_desc.arg_3 = transmisions_direction;
  _call_desc.arg_4 = &(::Proxy_Adapter::EZvalue&) frame_data;
  _call_desc.arg_5 = frame_length;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cunsigned_plong_n_cProxy__Adapter_mEZvalue_n_cunsigned_plong
class _0RL_cd_40eea1302de063aa_53000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40eea1302de063aa_53000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Proxy_Adapter::EZvalue_var arg_0_;
  Proxy_Adapter::EZvalue* arg_0;
  Proxy_Adapter::uint32 arg_1_;
  Proxy_Adapter::uint32* arg_1;
  Proxy_Adapter::EZstatus result;
};

void _0RL_cd_40eea1302de063aa_53000000::marshalArguments(cdrStream& _n)
{
  (const Proxy_Adapter::EZvalue&) *arg_0 >>= _n;
  *arg_1 >>= _n;

}

void _0RL_cd_40eea1302de063aa_53000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new Proxy_Adapter::EZvalue;
  (Proxy_Adapter::EZvalue&)arg_0_ <<= _n;
  arg_0 = &arg_0_.inout();
  (Proxy_Adapter::uint32&)arg_1_ <<= _n;
  arg_1 = &arg_1_;

}

void _0RL_cd_40eea1302de063aa_53000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  (const Proxy_Adapter::EZvalue&) *arg_0 >>= _n;
  *arg_1 >>= _n;

}

void _0RL_cd_40eea1302de063aa_53000000::unmarshalReturnedValues(cdrStream& _n)
{
  (Proxy_Adapter::EZstatus&)result <<= _n;
  (Proxy_Adapter::EZvalue&)*arg_0 <<= _n;
  (Proxy_Adapter::uint32&)*arg_1 <<= _n;

}

const char* const _0RL_cd_40eea1302de063aa_53000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40eea1302de063aa_63000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40eea1302de063aa_53000000* tcd = (_0RL_cd_40eea1302de063aa_53000000*)cd;
  Proxy_Adapter::_impl_NP3FrameHandl* impl = (Proxy_Adapter::_impl_NP3FrameHandl*) svnt->_ptrToInterface(Proxy_Adapter::NP3FrameHandl::_PD_repoId);
  tcd->result = impl->frameRead(*tcd->arg_0, *tcd->arg_1);


}

Proxy_Adapter::EZstatus Proxy_Adapter::_objref_NP3FrameHandl::frameRead(::Proxy_Adapter::EZvalue& frame_data, ::Proxy_Adapter::uint32& frame_length)
{
  _0RL_cd_40eea1302de063aa_53000000 _call_desc(_0RL_lcfn_40eea1302de063aa_63000000, "frameRead", 10);
  _call_desc.arg_0 = &(::Proxy_Adapter::EZvalue&) frame_data;
  _call_desc.arg_1 = &(::Proxy_Adapter::uint32&) frame_length;

  _invoke(_call_desc);
  return _call_desc.result;


}
Proxy_Adapter::_pof_NP3FrameHandl::~_pof_NP3FrameHandl() {}


omniObjRef*
Proxy_Adapter::_pof_NP3FrameHandl::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::Proxy_Adapter::_objref_NP3FrameHandl(ior, id);
}


::CORBA::Boolean
Proxy_Adapter::_pof_NP3FrameHandl::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::Proxy_Adapter::NP3FrameHandl::_PD_repoId) )
    return 1;
  
  return 0;
}

const Proxy_Adapter::_pof_NP3FrameHandl _the_pof_Proxy__Adapter_mNP3FrameHandl;

Proxy_Adapter::_impl_NP3FrameHandl::~_impl_NP3FrameHandl() {}


::CORBA::Boolean
Proxy_Adapter::_impl_NP3FrameHandl::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "testNP3FrameHandl") ) {

    _0RL_cd_40eea1302de063aa_00000000 _call_desc(_0RL_lcfn_40eea1302de063aa_23000000, "testNP3FrameHandl", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "frameSend") ) {

    _0RL_cd_40eea1302de063aa_33000000 _call_desc(_0RL_lcfn_40eea1302de063aa_43000000, "frameSend", 10, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "frameRead") ) {

    _0RL_cd_40eea1302de063aa_53000000 _call_desc(_0RL_lcfn_40eea1302de063aa_63000000, "frameRead", 10, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
Proxy_Adapter::_impl_NP3FrameHandl::_ptrToInterface(const char* id)
{
  if( id == ::Proxy_Adapter::NP3FrameHandl::_PD_repoId )
    return (::Proxy_Adapter::_impl_NP3FrameHandl*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::Proxy_Adapter::NP3FrameHandl::_PD_repoId) )
    return (::Proxy_Adapter::_impl_NP3FrameHandl*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
Proxy_Adapter::_impl_NP3FrameHandl::_mostDerivedRepoId()
{
  return ::Proxy_Adapter::NP3FrameHandl::_PD_repoId;
}

POA_Proxy_Adapter::StructConf::~StructConf() {}

POA_Proxy_Adapter::DevMonitor::~DevMonitor() {}

POA_Proxy_Adapter::TrafficMngt::~TrafficMngt() {}

POA_Proxy_Adapter::NP3FrameHandl::~NP3FrameHandl() {}

